Create code
Last login: Fri Oct  1 12:42:29 on ttys000
taniagallahar@tanias-air ~ % git clone git@github.com:tania12356/phase-0-git-basics-lab.git
fatal: destination path 'phase-0-git-basics-lab' already exists and is not an empty directory.
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab 
taniagallahar@tanias-air phase-0-git-basics-lab % npm install 

up to date, audited 202 packages in 3s

4 low severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
taniagallahar@tanias-air phase-0-git-basics-lab % npm test

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    1) has a README.md file in the my-repository folder

  the local repository
    2) has README.md as a tracked file
    3) has at least one commit
    4) has been pushed up to the remote repository


  2 passing (23ms)
  4 failing

  1) this lab
       has a README.md file in the my-repository folder:
     AssertionError: no README.md file found within "/my-repository": expected './my-repository/README.md' to exist
      at Function.assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)
      at Context.<anonymous> (test/index-test.js:17:17)
      at processImmediate (node:internal/timers:464:21)

  2) the local repository
       has README.md as a tracked file:
     AssertionError: no files are being tracked.  Use "git add ." to track all files in this repo: expected './my-repository/.git/index' to exist
      at Function.assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)
      at Context.<anonymous> (test/index-test.js:25:17)
      at processImmediate (node:internal/timers:464:21)

  3) the local repository
       has at least one commit:
     AssertionError: no commits were found.  Use "git commit -m" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:29:17)
      at processImmediate (node:internal/timers:464:21)

  4) the local repository
       has been pushed up to the remote repository:
     AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:33:17)
      at processImmediate (node:internal/timers:464:21)



taniagallahar@tanias-air phase-0-git-basics-lab % cd my-repository
taniagallahar@tanias-air my-repository % touch README.md
taniagallahar@tanias-air my-repository % git status
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	README.md

nothing added to commit but untracked files present (use "git add" to track)
taniagallahar@tanias-air my-repository % git add README.md
taniagallahar@tanias-air my-repository % git status
On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   README.md

taniagallahar@tanias-air my-repository % git commit -m "Initial commit"
[main (root-commit) a495fc5] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
taniagallahar@tanias-air my-repository % cd
taniagallahar@tanias-air ~ % npm test
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/taniagallahar/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/taniagallahar/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taniagallahar/.npm/_logs/2021-10-01T17_51_44_227Z-debug.log
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab % npm install                      
cd: too many arguments
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab      
taniagallahar@tanias-air phase-0-git-basics-lab % npm test

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    ✓ has a README.md file in the my-repository folder

  the local repository
    ✓ has README.md as a tracked file
    ✓ has at least one commit
    1) has been pushed up to the remote repository


  5 passing (17ms)
  1 failing

  1) the local repository
       has been pushed up to the remote repository:
     AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:33:17)
      at processImmediate (node:internal/timers:464:21)



taniagallahar@tanias-air phase-0-git-basics-lab % cd my-repository
taniagallahar@tanias-air my-repository % cd
taniagallahar@tanias-air ~ %  git branch -M main
fatal: not a git repository (or any of the parent directories): .git
taniagallahar@tanias-air ~ % cd my-repository
taniagallahar@tanias-air my-repository %  git branch -M main
taniagallahar@tanias-air my-repository % git remote add origin git@github.com:tania12356/my-repository.git
taniagallahar@tanias-air my-repository %  git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'github.com:tania12356/my-repository.git'
taniagallahar@tanias-air my-repository %  git branch -M main
taniagallahar@tanias-air my-repository %  git remote add origin git@github.com:tania12356/my-repository.git
error: remote origin already exists.
taniagallahar@tanias-air my-repository % git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'github.com:tania12356/my-repository.git'
taniagallahar@tanias-air my-repository % git push  origin main 
error: src refspec main does not match any
error: failed to push some refs to 'github.com:tania12356/my-repository.git'
taniagallahar@tanias-air my-repository %  git branch -M main

taniagallahar@tanias-air my-repository %  git remote add origin git@github.com:<git@github.com:tania12356/my-repository.git
zsh: no such file or directory: git@github.com:tania12356/my-repository.git
taniagallahar@tanias-air my-repository %  git remote add origin git@github.com:git@github.com:tania12356/my-repository.git
error: remote origin already exists.
taniagallahar@tanias-air my-repository %  git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'github.com:tania12356/my-repository.git'
taniagallahar@tanias-air my-repository %  rm -r github.com:tania12356/my-repository.git
rm: github.com:tania12356/my-repository.git: No such file or directory
taniagallahar@tanias-air my-repository % cd
taniagallahar@tanias-air ~ % echo "# my-repository" >> README.md
taniagallahar@tanias-air ~ % git init
Initialized empty Git repository in /Users/taniagallahar/.git/
taniagallahar@tanias-air ~ % git add README.md

taniagallahar@tanias-air ~ % git commit -m "first commit"
[main (root-commit) 4998f0b] first commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
taniagallahar@tanias-air ~ % git branch -M main

taniagallahar@tanias-air ~ % git remote add origin git@github.com:tania12356/my-repository.git

taniagallahar@tanias-air ~ % git push -u origin main

Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 229 bytes | 229.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:tania12356/my-repository.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab                         
taniagallahar@tanias-air phase-0-git-basics-lab % npm test

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    ✓ has a README.md file in the my-repository folder

  the local repository
    ✓ has README.md as a tracked file
    ✓ has at least one commit
    1) has been pushed up to the remote repository


  5 passing (18ms)
  1 failing

  1) the local repository
       has been pushed up to the remote repository:
     AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:33:17)
      at processImmediate (node:internal/timers:464:21)



taniagallahar@tanias-air phase-0-git-basics-lab % test
taniagallahar@tanias-air phase-0-git-basics-lab % npm test

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    ✓ has a README.md file in the my-repository folder

  the local repository
    ✓ has README.md as a tracked file
    ✓ has at least one commit
    1) has been pushed up to the remote repository


  5 passing (9ms)
  1 failing

  1) the local repository
       has been pushed up to the remote repository:
     AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:33:17)
      at processImmediate (node:internal/timers:464:21)



taniagallahar@tanias-air phase-0-git-basics-lab % cd
taniagallahar@tanias-air ~ %  git branch -M main

taniagallahar@tanias-air ~ % git remote add origin git@github.com:tania12356/my-repository.git
error: remote origin already exists.
taniagallahar@tanias-air ~ %  git push -u origin main

Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Branch 'main' set up to track remote branch 'main' from 'origin'.
Everything up-to-date
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab
taniagallahar@tanias-air phase-0-git-basics-lab % npm test

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    ✓ has a README.md file in the my-repository folder

  the local repository
    ✓ has README.md as a tracked file
    ✓ has at least one commit
    1) has been pushed up to the remote repository


  5 passing (10ms)
  1 failing

  1) the local repository
       has been pushed up to the remote repository:
     AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist
      at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)
      at Function.ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Function.assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)
      at Context.<anonymous> (test/index-test.js:33:17)
      at processImmediate (node:internal/timers:464:21)



taniagallahar@tanias-air phase-0-git-basics-lab % git init
Reinitialized existing Git repository in /Users/taniagallahar/phase-0-git-basics-lab/.git/
taniagallahar@tanias-air phase-0-git-basics-lab % cd my-repository
taniagallahar@tanias-air my-repository % git init
Reinitialized existing Git repository in /Users/taniagallahar/phase-0-git-basics-lab/my-repository/.git/
taniagallahar@tanias-air my-repository % git add README.md
taniagallahar@tanias-air my-repository % git commit -m "first commit"
On branch main
nothing to commit, working tree clean
taniagallahar@tanias-air my-repository % git branch -M main
taniagallahar@tanias-air my-repository % git remote add origin git@github.com:tania12356/my-repository.git
taniagallahar@tanias-air my-repository % git push -u origin main
To github.com:tania12356/my-repository.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:tania12356/my-repository.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
taniagallahar@tanias-air my-repository % git pull
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 209 bytes | 52.00 KiB/s, done.
From github.com:tania12356/my-repository
 * [new branch]      main       -> origin/main
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> main

taniagallahar@tanias-air my-repository % cd
taniagallahar@tanias-air ~ % phase-0-git-basics-lab
zsh: command not found: phase-0-git-basics-lab
taniagallahar@tanias-air ~ % cd-phase-0-git-basics-lab
zsh: command not found: cd-phase-0-git-basics-lab
taniagallahar@tanias-air ~ % cd phase-0-git-basics-lab
taniagallahar@tanias-air phase-0-git-basics-lab % npm test 

> git-basics-lab@1.0.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json



  this lab
    ✓ has a folder named my-repository
    ✓ has a valid git repository initialized for the my-repository folder
    ✓ has a README.md file in the my-repository folder

  the local repository
    ✓ has README.md as a tracked file
    ✓ has at least one commit
    ✓ has been pushed up to the remote repository


  6 passing (14ms)

taniagallahar@tanias-air phase-0-git-basics-lab % git add .
warning: adding embedded git repository: my-repository
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> my-repository
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached my-repository
hint: 
hint: See "git help submodule" for more information.
taniagallahar@tanias-air phase-0-git-basics-lab % git commit -m "Done with assignment"
[master 229d73f] Done with assignment
 2 files changed, 2036 insertions(+), 10 deletions(-)
 create mode 160000 my-repository
taniagallahar@tanias-air phase-0-git-basics-lab % git push origin master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 31.22 KiB | 3.90 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:tania12356/phase-0-git-basics-lab.git
   8a1e0ef..229d73f  master -> master
taniagallahar@tanias-air phase-0-git-basics-lab %